# Generated by Django 2.2.24 on 2022-05-17 02:00

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20220516_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='COP', max_digits=20, verbose_name='Valor de venta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valor_compra',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='COP', max_digits=20, null=True, verbose_name='Valor de compra'),
        ),
    ]
