# Generated by Django 2.2.24 on 2022-05-17 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20220516_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proyectos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Proyectos', verbose_name='Proyectos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
