# Generated by Django 2.0.1 on 2018-03-08 16:54

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican


def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Recursos humanos, ver aplicación", content_type = content_type, codename = 'recursos_humanos.ver'),

        Permission(name="Recursos humanos, ver contratistas", content_type=content_type, codename='recursos_humanos.contratistas.ver'),
        Permission(name="Recursos humanos, editar contratistas", content_type=content_type, codename='recursos_humanos.contratistas.editar'),
        Permission(name="Recursos humanos, crear contratistas", content_type=content_type, codename='recursos_humanos.contratistas.crear'),
        Permission(name="Recursos humanos, eliminar contratistas", content_type=content_type, codename='recursos_humanos.contratistas.eliminar'),
    ])


def create_groups(apps, schema_editor):

    #Consulta de contratistas
    consulta_contratistas, created = Group.objects.get_or_create(name = 'Recursos humanos, consulta contratistas')
    permisos_consulta_contratistas = Permission.objects.filter(codename__in = [
        'recursos_humanos.ver',
        'recursos_humanos.contratistas.ver'
    ])
    consulta_contratistas.permissions.add(*permisos_consulta_contratistas)

    #Edicion de contratistas
    edicion_contratistas, created = Group.objects.get_or_create(name='Recursos humanos, edición contratistas')
    permisos_edicion_contratistas = Permission.objects.filter(codename__in=[
        'recursos_humanos.ver',
        'recursos_humanos.contratistas.ver',
        'recursos_humanos.contratistas.crear',
        'recursos_humanos.contratistas.editar',
        'recursos_humanos.contratistas.eliminar'
    ])
    edicion_contratistas.permissions.add(*permisos_edicion_contratistas)



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratistas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cedula', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),

        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups),
    ]
