# Generated by Django 2.0.1 on 2018-03-09 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratistas',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratistas',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contratistas',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_actualizacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratistas',
            name='usuario_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_asociado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratistas',
            name='usuario_creacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
