# Generated by Django 2.0.1 on 2018-03-09 19:41

from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_contratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='soporte_liquidacion',
            field=models.FileField(default=1, upload_to=recursos_humanos.models.upload_dinamic_dir_liquidacion),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='soporte_renuncia',
            field=models.FileField(default=1, upload_to=recursos_humanos.models.upload_dinamic_dir_renuncia),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratos',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
