# Generated by Django 2.0.1 on 2018-03-09 20:03

from django.db import migrations
import recursos_humanos.models
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_auto_20180309_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='file',
            field=config.extrafields.PDFFileField(upload_to=recursos_humanos.models.upload_dinamic_dir),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='soporte_liquidacion',
            field=config.extrafields.PDFFileField(upload_to=recursos_humanos.models.upload_dinamic_dir_liquidacion),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='soporte_renuncia',
            field=config.extrafields.PDFFileField(upload_to=recursos_humanos.models.upload_dinamic_dir_renuncia),
        ),
    ]
