# Generated by Django 2.0.1 on 2018-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_auto_20180309_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='estado',
        ),
        migrations.AddField(
            model_name='contratos',
            name='ejecucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratos',
            name='ejecutado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratos',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratos',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
