# Generated by Django 2.0.1 on 2018-03-12 15:15

from django.db import migrations, models
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican

def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Recursos humanos, ver tipologia_soportes", content_type=content_type, codename='recursos_humanos.tipologia_soportes.ver'),
        Permission(name="Recursos humanos, editar tipologia_soportes", content_type=content_type, codename='recursos_humanos.tipologia_soportes.editar'),
        Permission(name="Recursos humanos, crear tipologia_soportes", content_type=content_type, codename='recursos_humanos.tipologia_soportes.crear'),
        Permission(name="Recursos humanos, eliminar tipologia_soportes", content_type=content_type, codename='recursos_humanos.tipologia_soportes.eliminar'),
    ])

def create_groups(apps, schema_editor):

    #Consulta de tipologia_soportes
    consulta_soportes, created = Group.objects.get_or_create(name = 'Recursos humanos, consulta tipologia_soportes')
    permisos_consulta_soportes = Permission.objects.filter(codename__in = [
        'recursos_humanos.ver',
        'recursos_humanos.tipologia_soportes.ver'
    ])
    consulta_soportes.permissions.add(*permisos_consulta_soportes)

    #Edicion de tipologia_soportes
    edicion_soportes, created = Group.objects.get_or_create(name='Recursos humanos, edición tipologia_soportes')
    permisos_edicion_soportes = Permission.objects.filter(codename__in=[
        'recursos_humanos.ver',
        'recursos_humanos.tipologia_soportes.ver',
        'recursos_humanos.tipologia_soportes.crear',
        'recursos_humanos.tipologia_soportes.editar',
        'recursos_humanos.tipologia_soportes.eliminar'
    ])
    edicion_soportes.permissions.add(*permisos_edicion_soportes)

class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_auto_20180309_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),

        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups),

    ]
