# Generated by Django 2.0.1 on 2018-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0009_soportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='Soportes',
            name='requerido',
            field=models.BooleanField(default=True),
        ),
    ]
