# Generated by Django 2.0.1 on 2018-03-12 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0010_soportes_requerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoportesContratos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='Soportes',
            name='categoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
