# Generated by Django 2.0.1 on 2018-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_auto_20180312_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupossoportes',
            name='soportes',
        ),
        migrations.AddField(
            model_name='grupossoportes',
            name='soportes',
            field=models.ManyToManyField(to='recursos_humanos.Soportes'),
        ),
    ]
