# Generated by Django 2.0.1 on 2018-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_auto_20180313_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupossoportes',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='soportes',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
