# Generated by Django 2.0.1 on 2018-03-13 15:46

from django.db import migrations, models
import django.db.models.deletion
import recursos_humanos.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0014_auto_20180313_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoportesContratos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_soporte_contrato)),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='grupo_soportes',
            field=models.ForeignKey(default='9f34ee35-de62-4fc2-9bd7-8e2c777f55fa', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.GruposSoportes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soportescontratos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.Contratos'),
        ),
        migrations.AddField(
            model_name='soportescontratos',
            name='soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.Soportes'),
        ),
    ]
