# Generated by Django 2.0.1 on 2018-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0018_auto_20180323_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratistas',
            name='tipo_identificacion',
            field=models.IntegerField(default=2),
        ),
    ]
