# Generated by Django 2.0.1 on 2018-04-04 14:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0019_contratistas_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratistas',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
