# Generated by Django 2.0.1 on 2018-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0020_auto_20180404_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='objeto_contrato',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
