# Generated by Django 2.0.1 on 2018-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0021_contratos_objeto_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(default='Ops', max_length=100),
            preserve_default=False,
        ),
    ]
