# Generated by Django 2.0.1 on 2018-04-10 16:59

from django.db import migrations, models
import django.db.models.deletion
import recursos_humanos.models
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican


def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Recursos humanos, ver certificaciones", content_type=content_type, codename='recursos_humanos.certificaciones.ver'),
        Permission(name="Recursos humanos, editar certificaciones", content_type=content_type, codename='recursos_humanos.certificaciones.editar'),
        Permission(name="Recursos humanos, crear certificaciones", content_type=content_type, codename='recursos_humanos.certificaciones.crear'),
        Permission(name="Recursos humanos, eliminar certificaciones", content_type=content_type, codename='recursos_humanos.certificaciones.eliminar'),
    ])

def create_groups(apps, schema_editor):

    #Consulta de contratistas
    consulta_contratistas, created = Group.objects.get_or_create(name = 'Recursos humanos, consulta certificaciones')
    permisos_consulta_contratistas = Permission.objects.filter(codename__in = [
        'recursos_humanos.ver',
        'recursos_humanos.certificaciones.ver'
    ])
    consulta_contratistas.permissions.add(*permisos_consulta_contratistas)

    #Edicion de contratistas
    edicion_contratistas, created = Group.objects.get_or_create(name='Recursos humanos, edición certificaciones')
    permisos_edicion_contratistas = Permission.objects.filter(codename__in=[
        'recursos_humanos.ver',
        'recursos_humanos.certificaciones.ver',
        'recursos_humanos.certificaciones.crear',
        'recursos_humanos.certificaciones.editar',
        'recursos_humanos.certificaciones.eliminar'
    ])
    edicion_contratistas.permissions.add(*permisos_edicion_contratistas)


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0022_contratos_tipo_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('word', models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_certificacion_word)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_certificacion_pdf)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.Contratistas')),
            ],
        ),

        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups),
    ]
