# Generated by Django 2.0.1 on 2018-04-11 16:42

from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0025_auto_20180411_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='html',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_certificacion_pdf),
        ),
    ]
