# Generated by Django 2.0.1 on 2018-04-12 14:13

from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0026_certificaciones_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='html_template',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_certificacion_pdf),
        ),
    ]
