# Generated by Django 2.0.1 on 2018-04-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0027_certificaciones_html_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='firma',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
