# Generated by Django 2.0.1 on 2018-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0028_certificaciones_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
