# Generated by Django 2.0.1 on 2018-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0029_contratos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='soportes',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
