# Generated by Django 2.0.1 on 2018-04-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0030_soportes_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportes',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
