# Generated by Django 2.0.1 on 2018-04-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0032_soportescontratos_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportescontratos',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
