# Generated by Django 2.0.1 on 2018-05-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0034_auto_20180502_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soportescontratos',
            old_name='obervacion',
            new_name='observacion',
        ),
    ]
