# Generated by Django 2.0.1 on 2018-05-04 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recursos_humanos.models
import config.extrafields
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican


def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Recursos humanos, ver hv", content_type=content_type, codename='recursos_humanos.hv.ver'),
        Permission(name="Recursos humanos, editar hv", content_type=content_type, codename='recursos_humanos.hv.editar'),
        Permission(name="Recursos humanos, crear hv", content_type=content_type, codename='recursos_humanos.hv.crear'),
        Permission(name="Recursos humanos, eliminar hv", content_type=content_type, codename='recursos_humanos.hv.eliminar'),
    ])

def create_groups(apps, schema_editor):

    #Consulta
    consulta, created = Group.objects.get_or_create(name = 'Recursos humanos, consulta hv')
    permisos_consulta = Permission.objects.filter(codename__in = [
        'recursos_humanos.hv.ver',
        'recursos_humanos.ver'
    ])
    consulta.permissions.add(*permisos_consulta)

    #Edicion
    edicion, created = Group.objects.get_or_create(name='Recursos humanos, edición hv')
    permisos_edicion = Permission.objects.filter(codename__in=[
        'recursos_humanos.ver',
        'recursos_humanos.hv.ver',
        'recursos_humanos.hv.crear',
        'recursos_humanos.hv.editar',
        'recursos_humanos.hv.eliminar'
    ])
    edicion.permissions.add(*permisos_edicion)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0035_auto_20180502_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('file', config.extrafields.PDFFileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_hv)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.Contratistas')),
            ],
        ),
        migrations.CreateModel(
            name='TrazabilidadHv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=200)),
                ('hv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trazabilidad_hv', to='recursos_humanos.Hv')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_trazabilidad_hv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups),
    ]
