# Generated by Django 2.0.1 on 2018-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0036_hv_trazabilidadhv'),
    ]

    operations = [
        migrations.AddField(
            model_name='hv',
            name='envio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
