# Generated by Django 2.0.1 on 2018-05-04 21:12

from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0037_auto_20180504_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='hv',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_excel),
        ),
    ]
