# Generated by Django 2.0.1 on 2018-05-04 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0038_hv_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hv',
            name='folio_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='folio_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_1',
            field=models.DateField(default=datetime.date(2018, 5, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='grado_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='institucion_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='nivel_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hv',
            name='titulo_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
