# Generated by Django 2.0.1 on 2018-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0040_auto_20180504_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hv',
            name='observaciones_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hv',
            name='observaciones_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
