# Generated by Django 2.0.1 on 2018-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0041_auto_20180504_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='hv',
            name='consecutivo_cargo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
