# Generated by Django 2.0.1 on 2018-05-12 00:46

from django.db import migrations
import recursos_humanos.models
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0042_hv_consecutivo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hv',
            name='file',
            field=config.extrafields.PDFFileField(blank=True, max_length=250, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_hv),
        ),
    ]
