# Generated by Django 2.0.1 on 2018-05-28 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0043_auto_20180511_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
