# Generated by Django 2.0.1 on 2018-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0044_contratos_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='fecha_legalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
