# Generated by Django 2.0.1 on 2018-05-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0045_contratos_fecha_legalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='soportescontratos',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
