# Generated by Django 2.0.1 on 2018-06-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0016_auto_20180413_1438'),
        ('recursos_humanos', '0046_soportescontratos_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Proyecto'),
        ),
    ]
