# Generated by Django 2.0.1 on 2018-06-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0047_contratos_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.Cargos'),
        ),
    ]
