# Generated by Django 2.0.1 on 2018-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0049_auto_20180608_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fecha_renuncia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
