# Generated by Django 2.1.3 on 2018-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0054_auto_20181116_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='delta',
            field=models.CharField(max_length=1000000),
        ),
    ]
