# Generated by Django 2.1.3 on 2019-02-19 20:51

from django.db import migrations, models
import recursos_humanos.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0055_auto_20181221_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaContratos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_carga_masiva_contratos)),
            ],
        ),
    ]
