# Generated by Django 2.1.5 on 2021-01-30 22:47

from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0056_cargamasivacontratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportescontratos',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_soporte_contrato),
        ),
    ]
