# Generated by Django 2.1.5 on 2021-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0059_auto_20210805_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hv',
            name='consecutivo_cargo',
        ),
        migrations.RemoveField(
            model_name='hv',
            name='excel',
        ),
        migrations.AlterField(
            model_name='hv',
            name='estado',
            field=models.CharField(default='Esperando aprobación', max_length=100),
        ),
    ]
