# Generated by Django 2.1.5 on 2021-08-09 15:20

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0060_auto_20210805_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='COP', max_digits=20),
        ),
    ]
