# Generated by Django 2.2.24 on 2021-10-01 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0064_collects_account_cuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuts',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha actualizacion'),
        ),
        migrations.AlterField(
            model_name='cuts',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_certificacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario actualizacion'),
        ),
    ]
