# Generated by Django 2.2.24 on 2021-10-14 21:16

import config.extrafields
from django.db import migrations, models
import recursos_humanos.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0065_auto_20211013_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='collects_account',
            name='estate_inform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='collects_account',
            name='file2',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=recursos_humanos.models.upload_dinamic_collects_account, verbose_name='Sin definir'),
        ),
        migrations.AlterField(
            model_name='collects_account',
            name='file4',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=recursos_humanos.models.upload_dinamic_collects_account, verbose_name='Registro de actividades firmada'),
        ),
    ]
