# Generated by Django 2.2.24 on 2021-10-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0067_auto_20211014_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='collects_account',
            name='estate_report',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado report'),
        ),
        migrations.AddField(
            model_name='collects_account',
            name='observaciones_report',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones cuentas de cobro'),
        ),
    ]
