# Generated by Django 2.2.24 on 2021-10-19 19:57

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0069_auto_20211019_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='transporte',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='COP', max_digits=20, null=True),
        ),
    ]
