# Generated by Django 2.2.24 on 2021-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0070_auto_20211019_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuts',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
