# Generated by Django 2.2.24 on 2021-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0071_auto_20211021_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuts',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
