# Generated by Django 2.2.24 on 2022-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0077_auto_20220120_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidations',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion'),
        ),
    ]
