# Generated by Django 2.2.24 on 2022-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0082_auto_20220128_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidations',
            name='estado_informe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='liquidations',
            name='estado_seguridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
