# Generated by Django 2.2.24 on 2022-02-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0084_otros_si'),
    ]

    operations = [
        migrations.AddField(
            model_name='otros_si',
            name='fecha_original',
            field=models.DateField(blank=True, null=True),
        ),
    ]
