# Generated by Django 2.2.24 on 2022-05-21 21:55

from django.db import migrations, models
import recursos_humanos.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0086_auto_20220502_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaOtrosSi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.upload_dinamic_dir_carga_masiva_otros_si)),
            ],
        ),
    ]
