# Generated by Django 2.0.1 on 2018-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20180427_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='nombre',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='ofertas',
            old_name='descripcion',
            new_name='experiencia',
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='aplicaciones',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='perfil',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertas',
            name='tipo_contrato',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
