# Generated by Django 2.0.1 on 2018-04-27 19:58

from django.db import migrations, models
import ofertas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_auto_20180427_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=ofertas.models.upload_dinamic_images),
        ),
    ]
