# Generated by Django 2.0.1 on 2018-04-27 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_ofertas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionesOfertas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('departamento_residencia', models.CharField(max_length=100)),
                ('municipio_residencia', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('educacion_basica', models.CharField(max_length=100)),
                ('educacion_secundaria', models.CharField(max_length=100)),
                ('fecha_grado_secundaria', models.DateField()),
                ('modalidad_academica_1', models.CharField(max_length=10)),
                ('semestres_aprobados_1', models.IntegerField()),
                ('graduado_1', models.CharField(max_length=10)),
                ('titulo_1', models.CharField(max_length=100)),
                ('mes_terminacion_1', models.CharField(max_length=100)),
                ('anio_terminacion_1', models.CharField(max_length=100)),
                ('numero_tarjeta_profesional_1', models.CharField(max_length=100)),
                ('fecha_expedicion_1', models.DateField()),
                ('modalidad_academica_2', models.CharField(blank=True, max_length=10, null=True)),
                ('semestres_aprobados_2', models.IntegerField(blank=True, null=True)),
                ('graduado_2', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo_2', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_terminacion_2', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_terminacion_2', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta_profesional_2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion_2', models.DateField(blank=True, null=True)),
                ('modalidad_academica_3', models.CharField(blank=True, max_length=10, null=True)),
                ('semestres_aprobados_3', models.IntegerField(blank=True, null=True)),
                ('graduado_3', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo_3', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_terminacion_3', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_terminacion_3', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta_profesional_3', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion_3', models.DateField(blank=True, null=True)),
                ('modalidad_academica_4', models.CharField(blank=True, max_length=10, null=True)),
                ('semestres_aprobados_4', models.IntegerField(blank=True, null=True)),
                ('graduado_4', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo_4', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_terminacion_4', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_terminacion_4', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta_profesional_4', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion_4', models.DateField(blank=True, null=True)),
                ('modalidad_academica_5', models.CharField(blank=True, max_length=10, null=True)),
                ('semestres_aprobados_5', models.IntegerField(blank=True, null=True)),
                ('graduado_5', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo_5', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_terminacion_5', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_terminacion_5', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta_profesional_5', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion_5', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
