# Generated by Django 2.0.1 on 2018-04-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_aplicacionesofertas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AplicacionesOfertas',
        ),
    ]
