# Generated by Django 2.0.1 on 2018-04-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20180429_1145'),
        ('ofertas', '0008_ofertas_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamentos_ofertas', to='usuarios.Departamentos'),
        ),
    ]
