# Generated by Django 2.0.1 on 2018-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20180429_1145'),
        ('ofertas', '0009_ofertas_departamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='departamentos',
            field=models.ManyToManyField(blank=True, null=True, related_name='departamentos_ofertas', to='usuarios.Departamentos'),
        ),
    ]
