# Generated by Django 2.0.1 on 2018-04-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20180429_1145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertas', '0012_remove_ofertas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionOferta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('obervacion', models.CharField(max_length=500)),
                ('departamentos', models.ManyToManyField(blank=True, null=True, related_name='departamentos_aplicacion', to='usuarios.Departamentos')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ofertas.Ofertas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
