# Generated by Django 2.0.1 on 2018-04-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_aplicacionoferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacionoferta',
            old_name='obervacion',
            new_name='observacion',
        ),
    ]
