# Generated by Django 2.0.1 on 2018-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0014_auto_20180429_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacionoferta',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
