# Generated by Django 2.0.1 on 2018-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0016_auto_20180430_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionoferta',
            name='aplica',
        ),
        migrations.RemoveField(
            model_name='aplicacionoferta',
            name='preseleccionado',
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='cualificacion_experiencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='cualificacion_perfil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='seleccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
