# Generated by Django 2.0.1 on 2018-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0017_auto_20180430_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacionoferta',
            old_name='seleccion',
            new_name='cualificacion_seleccion',
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='cualificacion_observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
