# Generated by Django 2.0.1 on 2018-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0018_auto_20180430_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacionoferta',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='departamentos_aplicacion', to='usuarios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='departamentos_ofertas', to='usuarios.Departamentos'),
        ),
    ]
