# Generated by Django 2.1.3 on 2019-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0019_auto_20180516_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
