# Generated by Django 2.1.3 on 2019-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_user_formulario_completo_ofertas'),
        ('ofertas', '0020_ofertas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='municipios',
            field=models.ManyToManyField(blank=True, related_name='municipios_ofertas', to='usuarios.Municipios'),
        ),
    ]
