# Generated by Django 2.0.1 on 2018-05-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiones',
            old_name='cantidad_radicados',
            new_name='cantidad_sedes',
        ),
    ]
