# Generated by Django 2.0.1 on 2018-05-03 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0002_auto_20180503_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ver', models.BooleanField(default=True)),
                ('dane_sede', models.CharField(max_length=100)),
                ('nombre_sede', models.CharField(max_length=200)),
                ('dane_ie', models.CharField(max_length=100)),
                ('nombre_ie', models.CharField(max_length=200)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formacion.Municipios')),
            ],
        ),
    ]
