# Generated by Django 2.0.1 on 2018-05-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0003_sedes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='cantidad_radicados',
            new_name='cantidad_sedes',
        ),
        migrations.RenameField(
            model_name='municipios',
            old_name='cantidad_radicados',
            new_name='cantidad_sedes',
        ),
    ]
