# Generated by Django 2.0.1 on 2018-05-07 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0005_auto_20180503_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentesFormados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('vigencia', models.CharField(max_length=100)),
                ('diplomado', models.CharField(max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formacion.Sedes')),
            ],
        ),
    ]
