# Generated by Django 2.0.1 on 2018-05-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0007_actualizaciondocentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diplomados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('niveles', models.IntegerField()),
                ('sesiones', models.IntegerField()),
                ('actividades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sesiones', models.IntegerField()),
                ('actividades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('actividades', models.IntegerField()),
            ],
        ),
    ]
