# Generated by Django 2.0.1 on 2018-05-11 22:20

from django.db import migrations, models
import formacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0010_actividades_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=formacion.models.upload_dinamic_dir_file_actividades),
        ),
    ]
