# Generated by Django 2.0.1 on 2018-05-28 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desplazamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='Solicitudes',
        ),
    ]
