# Generated by Django 2.0.1 on 2018-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplazamiento', '0003_desplazamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='desplazamiento',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desplazamiento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
