# Generated by Django 2.0.1 on 2018-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplazamiento', '0006_solicitudes_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
