# Generated by Django 2.0.1 on 2018-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplazamiento', '0007_solicitudes_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='desplazamiento',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
