# Generated by Django 2.0.1 on 2018-02-14 15:52

from django.db import migrations, models
import phonenumber_field.modelfields
import config.extrafields
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=usuarios.models.upload_dinamic_dir),
        ),
    ]
