# Generated by Django 2.0.1 on 2018-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_is_verificated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
