# Generated by Django 2.0.1 on 2018-03-06 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('usuarios', '0005_user_recovery_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoActivacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActivacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('generados', models.IntegerField()),
                ('usados', models.IntegerField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=usuarios.models.upload_dinamic_dir_paquete)),
                ('permissions', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='codigoactivacion',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.PaqueteActivacion'),
        ),
        migrations.AddField(
            model_name='codigoactivacion',
            name='permissions',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='codigoactivacion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
