# Generated by Django 2.0.1 on 2018-03-06 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180306_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoactivacion',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paqueteactivacion',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
