# Generated by Django 2.0.1 on 2018-03-07 13:50

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20180307_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteactivacion',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='Cuentas/Paquetes/'),
        ),
    ]
