# Generated by Django 2.0.1 on 2018-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20180307_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='short_description',
        ),
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
