# Generated by Django 2.0.1 on 2018-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20180307_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='link',
        ),
        migrations.AddField(
            model_name='notifications',
            name='short_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
