# Generated by Django 2.0.1 on 2018-04-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_departamentos_hojasdevida_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grado_educacion_basica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lugar_expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lugar_expedicion_municipio', to='usuarios.Municipios'),
        ),
        migrations.AddField(
            model_name='user',
            name='lugar_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lugar_nacimiento_municipio', to='usuarios.Municipios'),
        ),
        migrations.AddField(
            model_name='user',
            name='lugar_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lugar_residencia_municipio', to='usuarios.Municipios'),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel_educacion_basica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
