# Generated by Django 2.0.1 on 2018-04-28 22:21

from django.db import migrations
import config.extrafields
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20180428_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_hv',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=usuarios.models.upload_dinamic_dir),
        ),
    ]
