# Generated by Django 2.0.1 on 2018-04-29 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_user_photo_hv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modalidad', models.CharField(max_length=100)),
                ('semestres', models.IntegerField()),
                ('graduado', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_terminacion', models.DateField()),
                ('numero_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_titulo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
