# Generated by Django 2.0.1 on 2018-04-29 12:15

from django.db import migrations, models
import config.extrafields
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_titulos_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_hv',
        ),
        migrations.AddField(
            model_name='user',
            name='hv',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=usuarios.models.upload_dinamic_dir_hv),
        ),
        migrations.AddField(
            model_name='user',
            name='usar_photo_social_login',
            field=models.BooleanField(default=True),
        ),
    ]
