# Generated by Django 2.0.1 on 2018-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_user_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
