# Generated by Django 2.0.1 on 2018-04-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_user_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('tipo_empresa', models.CharField(max_length=100)),
                ('email_empresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Municipios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_experiencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
