# Generated by Django 2.0.1 on 2018-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_experiencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_ingreso',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_retiro',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
    ]
