# Generated by Django 2.0.1 on 2018-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20180429_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='formulario_completo_ofertas',
            field=models.BooleanField(default=False),
        ),
    ]
