# Generated by Django 2.1.3 on 2019-02-09 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_comunidadesafro_comunidadesindigenas_consejosafro_lenguasnativas_pueblosindigenas_resguardosindigena'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDiscapacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DificultadesPermanentesDiscapacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
