# Generated by Django 2.1.3 on 2019-02-18 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_categoriadiscapacidad_dificultadespermanentesdiscapacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementosDiscapacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposRehabilitacionDiscapacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
