# Generated by Django 2.1.5 on 2021-08-05 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consecutivo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to=reportes.models.upload_dinamic_dir_reporte)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
