# Generated by Django 2.0.1 on 2018-04-05 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportes.models
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican


def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Reportes, ver aplicación", content_type = content_type, codename = 'reportes.ver'),
    ])

def create_groups(apps, schema_editor):

    #Consulta de reportes
    consulta_reportes, created = Group.objects.get_or_create(name = 'Reportes, consulta reportes')
    permisos_consulta_reportes = Permission.objects.filter(codename__in = [
        'reportes.ver'
    ])
    consulta_reportes.permissions.add(*permisos_consulta_reportes)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=reportes.models.upload_dinamic_dir_reporte)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups)
    ]
