# Generated by Django 2.0.1 on 2018-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='consecutivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
