# Generated by Django 2.0.1 on 2018-04-09 19:42

from django.db import migrations, models
import reportes.models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reportes_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to=reportes.models.upload_dinamic_dir_reporte),
        ),
    ]
