# Generated by Django 2.0.1 on 2018-03-20 22:32

from django.db import migrations, models
import uuid
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from usuarios.models import ContentTypeSican


def create_permissions(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(ContentTypeSican)

    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(name="Dirección financiera, ver terceros", content_type=content_type, codename='direccion_financiera.terceros.ver'),
        Permission(name="Dirección financiera, editar terceros", content_type=content_type, codename='direccion_financiera.terceros.editar'),
        Permission(name="Dirección financiera, crear terceros", content_type=content_type, codename='direccion_financiera.terceros.crear'),
        Permission(name="Dirección financiera, eliminar terceros", content_type=content_type, codename='direccion_financiera.terceros.eliminar'),
    ])

def create_groups(apps, schema_editor):

    #Consulta de bancos
    consulta_terceros, created = Group.objects.get_or_create(name = 'Dirección financiera, consulta terceros')
    permisos_consulta_terceros = Permission.objects.filter(codename__in = [
        'direccion_financiera.ver',
        'direccion_financiera.terceros.ver'
    ])
    consulta_terceros.permissions.add(*permisos_consulta_terceros)

    #Edicion de bancos
    edicion_terceros, created = Group.objects.get_or_create(name='Dirección financiera, edición terceros')
    permisos_edicion_terceros = Permission.objects.filter(codename__in=[
        'direccion_financiera.ver',
        'direccion_financiera.terceros.ver',
        'direccion_financiera.terceros.crear',
        'direccion_financiera.terceros.editar',
        'direccion_financiera.terceros.eliminar'
    ])
    edicion_terceros.permissions.add(*permisos_edicion_terceros)


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),

        migrations.RunPython(create_permissions),
        migrations.RunPython(create_groups),

    ]
