# Generated by Django 2.0.1 on 2018-03-21 19:48

import direccion_financiera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0003_auto_20180321_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='estado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportes',
            name='estado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportes',
            name='plano',
            field=models.FileField(blank=True, null=True, upload_to=direccion_financiera.models.upload_dinamic_dir_soporte_plano),
        ),
    ]
