# Generated by Django 2.0.1 on 2018-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0008_reportes_file_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
