# Generated by Django 2.0.1 on 2018-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0012_reportes_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoReportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
