# Generated by Django 2.0.1 on 2018-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0014_reportes_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='longitud',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
