# Generated by Django 2.0.1 on 2018-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0015_bancos_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='longitud',
            field=models.CharField(max_length=100),
        ),
    ]
