# Generated by Django 2.0.1 on 2018-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0016_auto_20180413_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cuenta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
