# Generated by Django 2.0.1 on 2018-07-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0018_auto_20180713_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='update_datetime',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='usuario_creacion',
        ),
    ]
