# Generated by Django 2.0.1 on 2018-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0052_auto_20180614_1557'),
        ('direccion_financiera', '0019_auto_20180713_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamos',
            new_name='PagosDescontables',
        ),
        migrations.AddField(
            model_name='pagos',
            name='cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
