# Generated by Django 2.0.1 on 2018-07-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0021_auto_20180713_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizaciones',
            name='cuotas',
        ),
        migrations.AddField(
            model_name='amortizaciones',
            name='pago_descontado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Pagos'),
        ),
        migrations.AlterField(
            model_name='amortizaciones',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago_amortizacion', to='direccion_financiera.Pagos'),
        ),
    ]
