# Generated by Django 2.0.1 on 2018-07-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0022_auto_20180713_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizaciones',
            name='fecha_descontado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
