# Generated by Django 2.0.1 on 2018-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0023_amortizaciones_fecha_descontado'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizaciones',
            name='consecutivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
