# Generated by Django 2.0.1 on 2018-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0024_amortizaciones_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizaciones',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
