# Generated by Django 2.0.1 on 2018-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0025_amortizaciones_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='descuentos_pendientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='descuentos_pendientes_otro_valor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
