# Generated by Django 2.1.5 on 2019-10-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0026_auto_20180718_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='efectivo',
            field=models.BooleanField(default=False),
        ),
    ]
