# Generated by Django 2.1.5 on 2019-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0027_reportes_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='numero_contrato',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportes',
            name='numero_documento_equivalente',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
