# Generated by Django 2.1.5 on 2019-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0028_auto_20191113_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='numero_documento_equivalente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
