# Generated by Django 2.1.5 on 2020-04-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0032_auto_20200405_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='banco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cargo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cuenta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
