# Generated by Django 2.1.5 on 2020-12-09 20:32

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0033_auto_20200405_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='COP', max_digits=20),
        ),
    ]
