# Generated by Django 2.1.5 on 2021-08-17 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0035_auto_20210805_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('tax_number', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubroPresupuestalLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.RubroPresupuestal')),
            ],
        ),
        migrations.CreateModel(
            name='RubroPresupuestalLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise')),
                ('rubro_level_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.RubroPresupuestalLevel2')),
            ],
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='update_datetime',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='number',
        ),
        migrations.AlterField(
            model_name='reportes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='rubro_level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.RubroPresupuestalLevel2'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='rubro_level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.RubroPresupuestalLevel3'),
        ),
        migrations.AddField(
            model_name='rubropresupuestal',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise'),
        ),
        migrations.AddField(
            model_name='tiposoporte',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Enterprise'),
        ),
    ]
