# Generated by Django 2.1.5 on 2021-08-10 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0035_auto_20210805_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('numero', models.BigIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=100)),
            ],
        ),
    ]
