# Generated by Django 2.1.5 on 2021-08-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0037_auto_20210818_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubropresupuestallevel2',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='rubropresupuestallevel3',
            name='enterprise',
        ),
    ]
