# Generated by Django 2.1.5 on 2021-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0039_pagos_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
