# Generated by Django 2.1.5 on 2021-08-24 23:41

import direccion_financiera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0040_reportes_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportes',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportes',
            name='file_comprobante_egreso',
            field=models.FileField(blank=True, null=True, upload_to=direccion_financiera.models.upload_dinamic_dir_comprobante_egreso),
        ),
        migrations.AddField(
            model_name='reportes',
            name='numero_comprobante_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
