# Generated by Django 2.2.24 on 2021-08-30 17:27

import direccion_financiera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0045_enterprise_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='file_purchase_order',
            field=models.FileField(blank=True, null=True, upload_to=direccion_financiera.models.upload_dinamic_dir_soporte_file_purchase_order),
        ),
    ]
