# Generated by Django 2.2.24 on 2021-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0046_reportes_file_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='report_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
