# Generated by Django 2.2.24 on 2021-09-28 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0047_enterprise_report_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'Cuentas bancarias'},
        ),
        migrations.CreateModel(
            name='Projects_order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('enterprise', models.ManyToManyField(blank=True, to='direccion_financiera.Enterprise', verbose_name='Empresas')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
