# Generated by Django 2.2.24 on 2021-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0049_auto_20210928_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubropresupuestal',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='rubropresupuestal',
            name='enterprise',
            field=models.ManyToManyField(blank=True, to='direccion_financiera.Enterprise'),
        ),
    ]
