# Generated by Django 2.2.24 on 2021-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_financiera', '0050_auto_20210928_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
