# Generated by Django 2.1.3 on 2019-02-04 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0024_user_formulario_completo_ofertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogares',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('documento', models.BigIntegerField(unique=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('celular1', models.CharField(blank=True, max_length=100, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hogares_municipio_inscripcion', to='usuarios.Municipios')),
                ('municipio_residencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hogares_municipio_residencia', to='usuarios.Municipios')),
            ],
        ),
    ]
