# Generated by Django 2.1.3 on 2019-02-05 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField()),
                ('momentos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Momentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField()),
                ('instrumentos', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='momentos_componente', to='fest_2019.Componentes')),
            ],
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_omento', to='fest_2019.Momentos'),
        ),
    ]
