# Generated by Django 2.1.3 on 2019-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0002_auto_20190205_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentos',
            name='tipo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
