# Generated by Django 2.1.3 on 2019-02-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0006_hogares_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fest_2019.Componentes'),
        ),
    ]
