# Generated by Django 2.1.3 on 2019-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0009_auto_20190206_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='hogares_inscritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutas',
            name='meta_hogares',
            field=models.IntegerField(default=0),
        ),
    ]
