# Generated by Django 2.1.3 on 2019-02-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0011_cuposrutaobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuposrutaobject',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cupo_hogar', to='fest_2019.Hogares'),
        ),
    ]
