# Generated by Django 2.1.3 on 2019-02-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0012_auto_20190206_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogares',
            name='ruta_vinculacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_vinculacion_hogares', to='fest_2019.Rutas'),
        ),
    ]
