# Generated by Django 2.1.3 on 2019-02-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0013_hogares_ruta_vinculacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hogares',
            name='ruta',
        ),
        migrations.AddField(
            model_name='hogares',
            name='ruta_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta1_hogares', to='fest_2019.Rutas'),
        ),
        migrations.AddField(
            model_name='hogares',
            name='ruta_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta2_hogares', to='fest_2019.Rutas'),
        ),
        migrations.AddField(
            model_name='hogares',
            name='ruta_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta3_hogares', to='fest_2019.Rutas'),
        ),
        migrations.AddField(
            model_name='hogares',
            name='ruta_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta4_hogares', to='fest_2019.Rutas'),
        ),
    ]
