# Generated by Django 2.1.3 on 2019-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0014_auto_20190207_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogares',
            name='area_tierra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='area_unidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='cabeza_hogar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hogares',
            name='codigo_corregimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='codigo_familia_mfa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='codigo_vereda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='dependientes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='existe_mfa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='existe_unidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='fecha_hecho_victimizante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='genero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='hecho_victimizante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='id_archivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='id_elegible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='id_tipo_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='id_zona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='nombre_corregimiento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='nombre_vereda',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_mfa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_sisben',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_ssv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_tiempo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='puntaje_unidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='tiene_tierra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hogares',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hogares',
            name='zona_microfocalizada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
