# Generated by Django 2.1.3 on 2019-02-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0015_auto_20190207_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentos',
            name='novedades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='momentos',
            name='progreso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='momentos',
            name='valor_maximo',
            field=models.BooleanField(default=True),
        ),
    ]
