# Generated by Django 2.1.3 on 2019-02-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_2019', '0016_auto_20190207_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentosRutaObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ceacion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(max_length=100)),
                ('soporte', models.UUIDField()),
                ('observacion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField()),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_hogar', to='fest_2019.Hogares')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_momento', to='fest_2019.Momentos')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_ruta', to='fest_2019.Rutas')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_usuario_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_usuario_creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
