# Generated by Django 2.1.3 on 2019-02-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0017_instrumentosrutaobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentosrutaobject',
            old_name='ceacion',
            new_name='creacion',
        ),
    ]
