# Generated by Django 2.1.3 on 2019-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0018_auto_20190208_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='short_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
