# Generated by Django 2.1.3 on 2019-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0020_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='soporte',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
