# Generated by Django 2.1.3 on 2019-02-08 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0021_auto_20190208_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_usuario_actualizacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
