# Generated by Django 2.1.3 on 2019-02-08 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0022_auto_20190208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentosrutaobject',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
