# Generated by Django 2.1.3 on 2019-02-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0023_auto_20190208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentosrutaobject',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_instrumento', to='fest_2019.Instrumentos'),
        ),
    ]
