# Generated by Django 2.1.3 on 2019-02-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0024_instrumentosrutaobject_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_documento', to='fest_2019.Instrumentos'),
        ),
    ]
