# Generated by Django 2.1.3 on 2019-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0028_caracterizacioninicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='altitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='precision',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
