# Generated by Django 2.1.3 on 2019-02-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0029_auto_20190214_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='numero_libreta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='tiene_libreta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direccion_financiera.Bancos'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='categoria_discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.CategoriaDiscapacidad'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='comunidad_afro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ComunidadesAfro'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='comunidad_indigena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ComunidadesIndigenas'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='consejo_afro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ConsejosAfro'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='cual_lengua_afro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengua_afro', to='usuarios.LenguasNativas'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='cual_lengua_indigena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengua_indigena', to='usuarios.LenguasNativas'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='dificultades_permanentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.DificultadesPermanentesDiscapacidad'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='pueblo_indigena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.PueblosIndigenas'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='resguardo_indigena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ResguardosIndigenas'),
        ),
    ]
