# Generated by Django 2.1.3 on 2019-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_elementosdiscapacidad_tiposrehabilitaciondiscapacidad'),
        ('fest_2019', '0031_auto_20190218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='categoria_discapacidad',
            field=models.ManyToManyField(blank=True, to='usuarios.CategoriaDiscapacidad'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='dificultades_permanentes',
            field=models.ManyToManyField(blank=True, to='usuarios.DificultadesPermanentesDiscapacidad'),
        ),
        migrations.RemoveField(
            model_name='caracterizacioninicial',
            name='rehabilitacion',
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='rehabilitacion',
            field=models.ManyToManyField(blank=True, to='usuarios.TiposRehabilitacionDiscapacidad'),
        ),
        migrations.RemoveField(
            model_name='caracterizacioninicial',
            name='utiliza_actualmente',
        ),
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='utiliza_actualmente',
            field=models.ManyToManyField(blank=True, to='usuarios.ElementosDiscapacidad'),
        ),
    ]
