# Generated by Django 2.1.3 on 2019-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0032_auto_20190218_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacioninicial',
            name='recibe_alimentos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
