# Generated by Django 2.1.3 on 2019-02-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0033_caracterizacioninicial_recibe_alimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='actualmente_estudia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='bancarizacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='celular_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='departamento_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_atencion_caracterizacion_inicial', to='usuarios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='departamento_expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_expedicion_caracterizacion_inicial', to='usuarios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='departamento_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_nacimiento_caracterizacion_inicial', to='usuarios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='departamento_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_residencia_caracterizacion_inicial', to='usuarios.Departamentos'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='discapacidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='discapacitados_familia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='etnia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='grado_titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='mayores_60_anios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='menores_5_anios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='mujeres_gestantes_lactantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='municipio_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_atencion_caracterizacion_inicial', to='usuarios.Municipios'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='municipio_expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_expedicion_caracterizacion_inicial', to='usuarios.Municipios'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='municipio_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_nacimiento_caracterizacion_inicial', to='usuarios.Municipios'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='municipio_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_residencia_caracterizacion_inicial', to='usuarios.Municipios'),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='nivel_escolaridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='numero_personas_familia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='propiedad_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='recibe_alimentos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='regimen_seguridad_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='sabe_leer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='sabe_sumar_restar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='sexo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='tiene_cuidador',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='tiene_libreta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='tipo_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacioninicial',
            name='zona_residencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
