# Generated by Django 2.1.3 on 2019-03-25 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_2019', '0034_auto_20190218_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosCuentasRutas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rutas_aprobar', models.ManyToManyField(related_name='permisos_cuentas_aprobar', to='fest_2019.Rutas')),
                ('rutas_preaprobar', models.ManyToManyField(related_name='permisos_cuentas_preaprobar', to='fest_2019.Rutas')),
                ('rutas_ver', models.ManyToManyField(related_name='permisos_cuentas_ver', to='fest_2019.Rutas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
