# Generated by Django 2.1.3 on 2019-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0035_permisoscuentasrutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoscuentasrutas',
            name='rutas_aprobar',
            field=models.ManyToManyField(blank=True, related_name='permisos_cuentas_aprobar', to='fest_2019.Rutas'),
        ),
        migrations.AlterField(
            model_name='permisoscuentasrutas',
            name='rutas_preaprobar',
            field=models.ManyToManyField(blank=True, related_name='permisos_cuentas_preaprobar', to='fest_2019.Rutas'),
        ),
        migrations.AlterField(
            model_name='permisoscuentasrutas',
            name='rutas_ver',
            field=models.ManyToManyField(blank=True, related_name='permisos_cuentas_ver', to='fest_2019.Rutas'),
        ),
    ]
