# Generated by Django 2.1.3 on 2019-03-25 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_2019', '0036_auto_20190325_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentosTrazabilidadRutaObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trazabilidad_instrumento', to='fest_2019.InstrumentosRutaObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trazabilidad_instrumento_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
