# Generated by Django 2.1.3 on 2019-03-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0039_cortes_cuentascobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuposrutaobject',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fest_2019.Cortes'),
        ),
    ]
