# Generated by Django 2.1.3 on 2019-03-31 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_elementosdiscapacidad_tiposrehabilitaciondiscapacidad'),
        ('fest_2019', '0040_cuposrutaobject_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroNucleoHogar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_1', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('altitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('sexo', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_libreta', models.BooleanField(blank=True, default=False, null=True)),
                ('numero_libreta', models.CharField(blank=True, max_length=100, null=True)),
                ('identidad_genero', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_sexual', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('lengua_nativa_indigena', models.BooleanField(blank=True, null=True)),
                ('lengua_nativa_afro', models.BooleanField(blank=True, null=True)),
                ('discapacidad', models.BooleanField(blank=True, null=True)),
                ('registro_discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_cuidador', models.BooleanField(blank=True, null=True)),
                ('cuidador', models.CharField(blank=True, max_length=100, null=True)),
                ('parentezco', models.CharField(blank=True, max_length=100, null=True)),
                ('es_jefe', models.BooleanField(blank=True, null=True)),
                ('nivel_escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sabe_leer', models.BooleanField(blank=True, null=True)),
                ('sabe_sumar_restar', models.BooleanField(blank=True, null=True)),
                ('actualmente_estudia', models.BooleanField(blank=True, null=True)),
                ('recibe_alimentos', models.BooleanField(blank=True, null=True)),
                ('razon_no_estudia', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_no_estudia_otra', models.CharField(blank=True, max_length=100, null=True)),
                ('regimen_seguridad_social', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_discapacidad', models.ManyToManyField(blank=True, to='usuarios.CategoriaDiscapacidad')),
                ('comunidad_afro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ComunidadesAfro')),
                ('comunidad_indigena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ComunidadesIndigenas')),
                ('consejo_afro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ConsejosAfro')),
                ('cual_lengua_afro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengua_afro_miembro_nucleo', to='usuarios.LenguasNativas')),
                ('cual_lengua_indigena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengua_indigena_miembro_nucleo', to='usuarios.LenguasNativas')),
                ('departamento_expedicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_expedicion_miembro_nucleo', to='usuarios.Departamentos')),
                ('departamento_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_nacimiento_miembro_nucleo', to='usuarios.Departamentos')),
                ('dificultades_permanentes', models.ManyToManyField(blank=True, to='usuarios.DificultadesPermanentesDiscapacidad')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hogar_miembro_nucleo', to='fest_2019.Hogares')),
                ('municipio_expedicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_expedicion_miembro_nucleo', to='usuarios.Municipios')),
                ('municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_nacimiento_miembro_nucleo', to='usuarios.Municipios')),
                ('pueblo_indigena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.PueblosIndigenas')),
                ('rehabilitacion', models.ManyToManyField(blank=True, to='usuarios.TiposRehabilitacionDiscapacidad')),
                ('resguardo_indigena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ResguardosIndigenas')),
                ('utiliza_actualmente', models.ManyToManyField(blank=True, to='usuarios.ElementosDiscapacidad')),
            ],
        ),
    ]
