# Generated by Django 2.1.3 on 2019-06-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0042_documentoexcel_fotos2'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
