# Generated by Django 2.1.3 on 2019-06-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0043_componentes_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentes',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
