# Generated by Django 2.1.3 on 2019-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0044_auto_20190602_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='ruta',
            field=models.TextField(default=''),
        ),
    ]
