# Generated by Django 2.1.3 on 2019-06-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0045_componentes_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='valor_pagado',
            field=models.IntegerField(default=0),
        ),
    ]
