# Generated by Django 2.1.3 on 2019-06-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0046_componentes_valor_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuposrutaobject',
            name='translado',
            field=models.BooleanField(default=False),
        ),
    ]
