# Generated by Django 2.1.3 on 2019-07-17 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_2019', '0048_archivorarzip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionesInstrumentoRutaObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fest_2019.InstrumentosRutaObject')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_observacion_usuario_creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
