# Generated by Django 2.1.5 on 2019-11-08 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_elementosdiscapacidad_tiposrehabilitaciondiscapacidad'),
        ('fest_2019', '0050_fotos6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('resguardo', models.CharField(max_length=100)),
                ('comunidad', models.CharField(max_length=100)),
                ('lenguas', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hcontactos_municipio', to='usuarios.Municipios')),
            ],
        ),
    ]
