# Generated by Django 2.1.5 on 2019-12-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0051_contactos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentosrutaobject',
            name='hogar',
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='nivel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentosrutaobject',
            name='hogares',
            field=models.ManyToManyField(blank=True, related_name='instrumento_hogar', to='fest_2019.Hogares'),
        ),
    ]
