# Generated by Django 2.1.5 on 2019-12-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0053_auto_20191214_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='meta_hogares',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='meta_vinculacion',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='peso_encuentros',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='peso_otros',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='peso_visitas',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_actividades',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_actividades_currency',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_transporte_vinculacion',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_transporte_vinculacion_currency',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_vinculacion',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='valor_vinculacion_currency',
        ),
    ]
