# Generated by Django 2.1.5 on 2019-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0055_rutas_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='valores_actividades',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
