# Generated by Django 2.1.5 on 2019-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0057_auto_20191215_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hogares',
            field=models.ManyToManyField(blank=True, related_name='hogares_documento', to='fest_2019.Hogares'),
        ),
    ]
