# Generated by Django 2.1.5 on 2019-12-16 05:01

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import fest_2019.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_elementosdiscapacidad_tiposrehabilitaciondiscapacidad'),
        ('fest_2019', '0059_actasocializacioncomunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaVinculacionHogar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_diligenciamiento', models.DateField()),
                ('resguado_indigena_consejo_comunitario', models.CharField(max_length=100)),
                ('nombre_comunidad', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(max_length=100)),
                ('documento_representante', models.IntegerField()),
                ('nombre_representante', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=300)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2019.models.upload_dinamic_acta_vinculacion_hogar)),
                ('hogares', models.ManyToManyField(blank=True, related_name='hogares_acta_vinculacion_hogar', to='fest_2019.Hogares')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_acta_vinculacion_hogar', to='fest_2019.Instrumentos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_acta_vinculacion_hogar', to='usuarios.Municipios')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_acta_vinculacion_hogar', to='fest_2019.Rutas')),
            ],
        ),
    ]
