# Generated by Django 2.1.5 on 2019-12-18 02:33

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import fest_2019.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_elementosdiscapacidad_tiposrehabilitaciondiscapacidad'),
        ('fest_2019', '0060_actavinculacionhogar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaSocializacionConcertacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_diligenciamiento', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
                ('resguado_indigena_consejo_comunitario', models.CharField(max_length=100)),
                ('nombre_comunidad', models.CharField(max_length=100)),
                ('nombre_representante', models.CharField(max_length=200)),
                ('datos_contacto_representante', models.CharField(max_length=200)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_concertacion)),
                ('file2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_concertacion)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_concertacion)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_concertacion)),
                ('hogares', models.ManyToManyField(blank=True, related_name='hogares_acta_socializacion_concertacion', to='fest_2019.Hogares')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_acta_socializacion_concertacion', to='fest_2019.Instrumentos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_acta_socializacion_concertacion', to='usuarios.Municipios')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_acta_socializacion_concertacion', to='fest_2019.Rutas')),
            ],
        ),
    ]
