# Generated by Django 2.1.5 on 2019-12-18 03:19

import config.extrafields
from django.db import migrations
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0061_actasocializacionconcertacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actasocializacioncomunidades',
            name='file2',
            field=config.extrafields.ContentTypeRestrictedFileField(default='', max_length=255, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_comunidades),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actasocializacioncomunidades',
            name='foto1',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_comunidades),
        ),
        migrations.AddField(
            model_name='actasocializacioncomunidades',
            name='foto2',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_comunidades),
        ),
    ]
