# Generated by Django 2.1.5 on 2019-12-18 03:42

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import fest_2019.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0063_actavinculacionhogar_file2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCaracterizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2019.models.upload_dinamic_formulario_caracterizacion)),
                ('file2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2019.models.upload_dinamic_formulario_caracterizacion)),
                ('hogares', models.ManyToManyField(blank=True, related_name='hogares_formulario_caracterizacion', to='fest_2019.Hogares')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_formulario_caracterizacion', to='fest_2019.Instrumentos')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_formulario_caracterizacion', to='fest_2019.Rutas')),
            ],
        ),
    ]
