# Generated by Django 2.1.5 on 2019-12-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0065_fichaicoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaicoe',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='fichaicoe',
            name='foto2',
        ),
    ]
