# Generated by Django 2.1.5 on 2020-01-13 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0070_cuposrutaobject_instrumento_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuposrutaobject',
            name='instrumento_object',
        ),
        migrations.AddField(
            model_name='instrumentosrutaobject',
            name='cupo_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fest_2019.CuposRutaObject'),
        ),
    ]
