# Generated by Django 2.1.5 on 2020-01-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0072_auto_20200126_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisoscuentasrutas',
            name='rutas_preaprobar',
        ),
    ]
