# Generated by Django 2.1.5 on 2020-02-19 21:40

import config.extrafields
from django.db import migrations
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0073_remove_permisoscuentasrutas_rutas_preaprobar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actasocializacioncomunidades',
            name='file3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_acta_socializacion_comunidades),
        ),
    ]
