# Generated by Django 2.1.5 on 2020-04-15 23:55

import config.extrafields
from django.db import migrations
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0074_actasocializacioncomunidades_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaicoe',
            name='file3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_icoe),
        ),
        migrations.AddField(
            model_name='fichaicoe',
            name='foto1',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_icoe),
        ),
        migrations.AddField(
            model_name='fichaicoe',
            name='foto2',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_icoe),
        ),
        migrations.AddField(
            model_name='fichaicoe',
            name='foto3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_icoe),
        ),
    ]
