# Generated by Django 2.1.5 on 2020-04-16 01:09

import config.extrafields
from django.db import migrations
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0075_auto_20200415_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavisiondesarrollo',
            name='foto3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_vision_desarrollo),
        ),
        migrations.AddField(
            model_name='fichavisiondesarrollo',
            name='foto4',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_vision_desarrollo),
        ),
        migrations.AddField(
            model_name='fichavisiondesarrollo',
            name='foto5',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_vision_desarrollo),
        ),
    ]
