# Generated by Django 2.1.5 on 2020-04-16 01:37

import config.extrafields
from django.db import migrations
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0076_auto_20200415_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticocomunitario',
            name='file4',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_diagnostico_comunitario),
        ),
        migrations.AddField(
            model_name='diagnosticocomunitario',
            name='file5',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_diagnostico_comunitario),
        ),
        migrations.AddField(
            model_name='diagnosticocomunitario',
            name='foto3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_diagnostico_comunitario),
        ),
        migrations.AddField(
            model_name='diagnosticocomunitario',
            name='foto4',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_diagnostico_comunitario),
        ),
        migrations.AddField(
            model_name='diagnosticocomunitario',
            name='foto5',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_diagnostico_comunitario),
        ),
    ]
