# Generated by Django 2.1.5 on 2020-04-24 16:25

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20200424_1125'),
        ('fest_2019', '0078_proyectosapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='actividad_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aliado_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aliado_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aliado_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aliado_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='anexo_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='anexo_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='anexo_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='anexo_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aporte_aliado_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aporte_aliado_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aporte_aliado_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='aporte_aliado_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='cedula_funcionario',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='cedula_representante_comite',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='cedula_representante_consejo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='codigo_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='concepto_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='conservacion_manejo_ambiental',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='convenio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='datos_contacto_aliado_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='datos_contacto_aliado_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='datos_contacto_aliado_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='datos_contacto_aliado_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='duracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='file',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='indicador_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='linea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='medio_verificacion_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_1_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_2_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_3_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_4_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_5_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='mes_6_9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='meta_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_ficha_proyecto', to='usuarios.Municipios'),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_aliado_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_aliado_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_aliado_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_aliado_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_comunidad',
            field=models.ManyToManyField(blank=True, to='usuarios.ComunidadesProyectosIraca'),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_funcionario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_representante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_representante_comite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='nombre_representante_consejo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='numero_hogares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='objetivo_especifico_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='objetivo_especifico_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='objetivo_especifico_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='objetivo_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='observaciones_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='producto_servicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='resguado_indigena_consejo_comunitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ConsejosResguardosProyectosIraca'),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='riesgos_acciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='sustentabilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='ubicacion_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='unidad_medida_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
