# Generated by Django 2.1.5 on 2020-04-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0079_auto_20200424_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosapi',
            name='convenio',
            field=models.TextField(default='213-19'),
        ),
    ]
