# Generated by Django 2.1.5 on 2020-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0080_auto_20200424_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='criterios_socioculturales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
