# Generated by Django 2.1.5 on 2020-05-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0082_auto_20200424_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='tipo_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
