# Generated by Django 2.1.5 on 2020-05-03 04:07

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0084_auto_20200502_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='file2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='file3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='file4',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='file5',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AlterField(
            model_name='proyectosapi',
            name='convenio',
            field=models.TextField(default='223-29'),
        ),
        migrations.AlterField(
            model_name='proyectosapi',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='COP', max_digits=20),
        ),
    ]
