# Generated by Django 2.1.5 on 2020-05-03 04:32

from django.db import migrations, models
import fest_2019.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0086_auto_20200502_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosapi',
            name='file2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AlterField(
            model_name='proyectosapi',
            name='file3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AlterField(
            model_name='proyectosapi',
            name='file4',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
        migrations.AlterField(
            model_name='proyectosapi',
            name='file5',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=fest_2019.models.upload_dinamic_ficha_proyecto),
        ),
    ]
