# Generated by Django 2.1.5 on 2020-05-09 21:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0088_auto_20200503_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='flujo_caja',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
