# Generated by Django 2.1.5 on 2020-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0089_proyectosapi_flujo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_5_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_5_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_6_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_5_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_5_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_6_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_5_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_5_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_6_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
