# Generated by Django 2.1.5 on 2020-05-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0090_auto_20200526_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='estado',
            field=models.CharField(default='Cargado', max_length=200),
        ),
    ]
