# Generated by Django 2.1.5 on 2020-05-27 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20200424_1125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fest_2019', '0092_observacionesproyectosapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosCuentasDepartamentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Departamentos')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
