# Generated by Django 2.1.5 on 2020-05-29 20:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0095_auto_20200527_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferenciacionApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
