# Generated by Django 2.1.5 on 2020-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0096_georeferenciacionapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_5_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='acciones_6_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='priorizacion_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_5_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='problematica_6_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_5_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectosapi',
            name='proyectos_potenciales_6_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
