# Generated by Django 2.1.5 on 2020-06-01 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2019', '0097_auto_20200531_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='georeferenciacionapi',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
