# Generated by Django 2.2.24 on 2021-09-03 14:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Types', verbose_name='Tipo de Acta'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=200)),
                ('movil', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('reservation', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('languahe', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('meting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Meetings')),
            ],
        ),
    ]
