# Generated by Django 2.2.24 on 2021-09-03 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20200424_1125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iraca', '0002_auto_20210903_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document', models.BigIntegerField(unique=True)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('movil1', models.CharField(blank=True, max_length=100, null=True)),
                ('movil2', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality_attention', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='household_municipality_attention_iraca_2021', to='usuarios.Municipios')),
                ('municipality_residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='household_municipality_residence_iraca_2021', to='usuarios.Municipios')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('consecutive', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('consecutive', models.IntegerField()),
                ('instruments', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('novelty', models.BooleanField(default=True)),
                ('progress', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRouteInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('support', models.UUIDField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('estate', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('consecutive', models.IntegerField(blank=True, null=True)),
                ('creacion_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_creation_user_iraca_2021', to=settings.AUTH_USER_MODEL)),
                ('households', models.ManyToManyField(blank=True, related_name='instrument_household_iraca_2021', to='iraca.Households')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumentroute_instrument_iraca_2021', to='iraca.Instruments')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_route_moment_iraca_2021', to='iraca.Moments')),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='reservation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('novelties', models.IntegerField(default=0)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(blank=True, max_length=100)),
                ('regitered_household', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creation_user_route_iraca_2021', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_route_iraca_2021', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationsInstrumentRouteObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.ObjectRouteInstrument')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_observation_creation_user_iraca_2021', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objectrouteinstrument',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_route_iraca_2021', to='iraca.Routes'),
        ),
        migrations.AddField(
            model_name='objectrouteinstrument',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_update_user_iraca_2021', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstrumentTraceabilityRouteObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traceability_instrument_iraca_2021', to='iraca.ObjectRouteInstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traceability_instrument_user_iraca_2021', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instruments',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_moment_iraca_2021', to='iraca.Moments'),
        ),
        migrations.AddField(
            model_name='households',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='routes_iraca_2021', to='iraca.Routes'),
        ),
    ]
