# Generated by Django 2.2.24 on 2021-09-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0003_auto_20210903_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
