# Generated by Django 2.2.24 on 2021-09-07 14:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0004_routes_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotasRouteObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('estate', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('moment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quota_moment_iraca_2021', to='iraca.Moments')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quota_route_iraca_2021', to='iraca.Routes')),
            ],
        ),
    ]
