# Generated by Django 2.2.24 on 2021-09-07 16:01

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import iraca.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0005_quotasrouteobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=iraca.models.upload_dinamic_iraca_2021)),
                ('households', models.ManyToManyField(blank=True, related_name='households_document_iraca_2021', to='iraca.Households')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_document_iraca_2021', to='iraca.Instruments')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='route_document_iraca_2021', to='iraca.Routes')),
            ],
        ),
    ]
