# Generated by Django 2.2.24 on 2021-09-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0006_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='moments',
            name='type_moment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routes',
            name='novelties_form',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routes',
            name='progress_form',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
