# Generated by Django 2.2.24 on 2021-09-17 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0007_auto_20210908_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='households',
            field=models.ManyToManyField(blank=True, related_name='households_document_iraca_2021', to='iraca.Households', verbose_name='Hogares'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_document_iraca_2021', to='iraca.Instruments', verbose_name='Instrumentos'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='route_document_iraca_2021', to='iraca.Routes', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='consecutive',
            field=models.IntegerField(verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='level',
            field=models.CharField(max_length=100, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_moment_iraca_2021', to='iraca.Moments', verbose_name='Momento'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='short_name',
            field=models.CharField(max_length=100, verbose_name='Nombre corto'),
        ),
    ]
