# Generated by Django 2.2.24 on 2021-09-27 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20200424_1125'),
        ('iraca', '0008_auto_20210917_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resguards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resguard_municipality_iraca_2021', to='usuarios.Municipios')),
            ],
        ),
    ]
