# Generated by Django 2.2.24 on 2021-09-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0009_resguards'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='resguard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resguard_route_iraca_2021', to='iraca.Resguards'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
