# Generated by Django 2.2.24 on 2021-10-26 14:42

from django.db import migrations, models
import iraca.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0010_auto_20210927_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaHogares',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=iraca.models.upload_dinamic_dir_carga_masiva_hogares)),
            ],
        ),
    ]
