# Generated by Django 2.2.24 on 2022-06-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20200424_1125'),
        ('iraca', '0011_cargamasivahogares'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_municipality_iraca_2021', to='usuarios.Municipios'),
        ),
    ]
