# Generated by Django 2.2.24 on 2022-06-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0012_certificates_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resguards',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_municipality_iraca_2021', to='iraca.Certificates'),
        ),
        migrations.AddField(
            model_name='resguards',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resguards',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resguard_municipality_iraca_2021', to='usuarios.Municipios'),
        ),
    ]
