# Generated by Django 2.2.24 on 2022-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0014_comunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='comunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comunity_route_iraca_2021', to='iraca.Comunity'),
        ),
    ]
