# Generated by Django 2.2.24 on 2022-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0015_routes_comunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
