# Generated by Django 2.2.24 on 2022-06-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0016_auto_20220604_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='resguard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Resguards'),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Meetings'),
        ),
    ]
