# Generated by Django 2.2.24 on 2022-06-11 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0017_auto_20220611_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
