# Generated by Django 2.2.24 on 2022-06-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0018_actas'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Actas', verbose_name='Tipo de Acta'),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iraca.Types', verbose_name='Tipo de Acta'),
        ),
    ]
