# Generated by Django 2.2.24 on 2022-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraca', '0022_auto_20220615_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='type_transversar',
            field=models.BooleanField(default=False),
        ),
    ]
