# Generated by Django 2.2.24 on 2022-06-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iraca', '0023_milestones_type_transversar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiltonesTraceabilityObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('miltone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traceability_milestone_iraca_2022', to='iraca.Milestones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traceability_milestone_user_iraca_2022', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
