# Generated by Django 2.1.5 on 2021-01-27 01:46

import config.extrafields
from django.db import migrations, models
import django.db.models.deletion
import fest_2020_.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2020_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGeneral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2020_.models.upload_dinamic_documento_general)),
                ('file2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=fest_2020_.models.upload_dinamic_documento_general)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2020_.models.upload_dinamic_documento_general)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2020_.models.upload_dinamic_documento_general)),
                ('hogares', models.ManyToManyField(blank=True, related_name='hogares_documentogeneral', to='fest_2020_.Hogares')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumento_documentogeneral', to='fest_2020_.Instrumentos')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_documentogeneral', to='fest_2020_.Rutas')),
            ],
        ),
    ]
