# Generated by Django 2.1.5 on 2021-01-27 01:48

import config.extrafields
from django.db import migrations
import fest_2020_.models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_2020_', '0002_documentogeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentogeneral',
            name='file',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2020_.models.upload_dinamic_documento_general),
        ),
        migrations.AlterField(
            model_name='documentogeneral',
            name='file2',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=fest_2020_.models.upload_dinamic_documento_general),
        ),
    ]
