# Generated by Django 2.0.1 on 2018-06-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0002_auto_20180605_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='tipologia',
        ),
    ]
