# Generated by Django 2.0.1 on 2018-06-08 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0003_remove_actividades_tipologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='actividadesradicados',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='actividadesruta',
            name='actividad',
        ),
        migrations.DeleteModel(
            name='Actividades',
        ),
    ]
