# Generated by Django 2.0.1 on 2018-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0008_auto_20180608_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='tipo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
