# Generated by Django 2.0.1 on 2018-06-14 20:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0011_auto_20180614_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregablerutaobject',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas'),
        ),
        migrations.AlterField(
            model_name='entregablerutaobject',
            name='valor',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='COP', max_digits=10, null=True),
        ),
    ]
