# Generated by Django 2.0.1 on 2018-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0013_auto_20180615_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentos',
            name='icon',
            field=models.CharField(default='accessibility', max_length=100),
            preserve_default=False,
        ),
    ]
