# Generated by Django 2.0.1 on 2018-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0014_momentos_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregablerutaobject',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
