# Generated by Django 2.0.1 on 2018-06-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0015_entregablerutaobject_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
