# Generated by Django 2.0.1 on 2018-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0016_entregables_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregablerutaobject',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
