# Generated by Django 2.0.1 on 2018-06-22 13:51

import cpe_2018.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0018_entregablerutaobject_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retoma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('radicado', models.CharField(max_length=100)),
                ('dane', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('sede_educativa', models.CharField(max_length=100)),
                ('bolsas', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('trc', models.IntegerField()),
                ('lcd', models.IntegerField()),
                ('portatil', models.IntegerField()),
                ('impresora', models.IntegerField()),
                ('tableta', models.IntegerField()),
                ('perifericos', models.IntegerField()),
                ('rector', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField()),
                ('file', models.FileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas)),
                ('foto1', models.ImageField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas)),
                ('foto2', models.ImageField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas)),
                ('foto3', models.ImageField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas)),
                ('foto4', models.ImageField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Municipios')),
            ],
        ),
        migrations.AddField(
            model_name='entregablerutaobject',
            name='soporte',
            field=models.CharField(default='', max_length=100),
        ),
    ]
