# Generated by Django 2.0.1 on 2018-06-22 14:03

import cpe_2018.models
from django.db import migrations
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0019_auto_20180622_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retoma',
            name='file',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto1',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto2',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto3',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto4',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
    ]
