# Generated by Django 2.0.1 on 2018-06-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0020_auto_20180622_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='retoma',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas'),
            preserve_default=False,
        ),
    ]
