# Generated by Django 2.0.1 on 2018-06-22 16:39

import cpe_2018.models
from django.db import migrations, models
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0021_retoma_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='retoma',
            name='foto5',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retoma',
            name='foto6',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_retomas),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retoma',
            name='celular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='dane',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='impresora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='lcd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='perifericos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='portatil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='radicado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='sede_educativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='tableta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='trc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
