# Generated by Django 2.0.1 on 2018-06-22 19:26

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0022_auto_20180622_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRetoma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='retoma',
            name='bolsas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto5',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='foto6',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_retomas),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='impresora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='lcd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='perifericos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='portatil',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='tableta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='trc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroretoma',
            name='retoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Retoma'),
        ),
        migrations.AddField(
            model_name='registroretoma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_retoma', to=settings.AUTH_USER_MODEL),
        ),
    ]
