# Generated by Django 2.0.1 on 2018-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0024_retoma_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='retoma',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
    ]
