# Generated by Django 2.0.1 on 2018-06-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0025_retoma_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retoma',
            name='actualizacion',
        ),
    ]
