# Generated by Django 2.0.1 on 2018-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0027_actapostulacion_basedatospostulante_eventoinstitucional_eventomunicipal_registroactapostulacion_regi'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='peso',
            field=models.IntegerField(default=1),
        ),
    ]
