# Generated by Django 2.0.1 on 2018-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0029_auto_20180626_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='actapostulacion',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basedatospostulante',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventoinstitucional',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventomunicipal',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
    ]
