# Generated by Django 2.0.1 on 2018-06-27 17:03

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0030_auto_20180626_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDirectorioMunicipios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_acta_postulacion)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionDirectorioSedes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_acta_postulacion)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaTalleres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_acta_postulacion)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActualizacionDirectorioMunicipios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('actualizacion_directorio_municipios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ActualizacionDirectorioSedes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_actualizacion_directorio_municipios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActualizacionDirectorioSedes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('actualizacion_directorio_sedes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ActualizacionDirectorioSedes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_actualizacion_directorio_sedes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCronogramaTalleres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('cronograma_talleres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ActualizacionDirectorioSedes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_cronograma_talleres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
