# Generated by Django 2.0.1 on 2018-06-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0031_actualizaciondirectoriomunicipios_actualizaciondirectoriosedes_cronogramatalleres_registroactualizac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocronogramatalleres',
            name='cronograma_talleres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.CronogramaTalleres'),
        ),
    ]
