# Generated by Django 2.0.1 on 2018-06-27 20:38

import cpe_2018.models
from django.db import migrations
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0032_auto_20180627_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoinstitucional',
            name='registro_fotografico',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_evento_institucional),
        ),
    ]
