# Generated by Django 2.0.1 on 2018-06-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0033_auto_20180627_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactualizaciondirectoriomunicipios',
            name='actualizacion_directorio_municipios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ActualizacionDirectorioMunicipios'),
        ),
    ]
