# Generated by Django 2.0.1 on 2018-06-28 20:30

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0035_auto_20180627_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegalizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_documento_legalizacion)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoLegalizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('documento_legalizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoLegalizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_documento_legalizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRelatoriaGraduacionDocentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RelatoriaGraduacionDocentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relatoria', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_graduacion_docentes)),
                ('registro_fotografico', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_evento_institucional)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.AddField(
            model_name='registrorelatoriagraduaciondocentes',
            name='relatoria_graduacion_docentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RelatoriaGraduacionDocentes'),
        ),
        migrations.AddField(
            model_name='registrorelatoriagraduaciondocentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_relatoria_graduacion_docentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
