# Generated by Django 2.0.1 on 2018-07-03 14:36

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0036_auto_20180628_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuenticosTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_cuenticos_taller_apertura)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='DibuarteTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_dibuarte_taller_contenidos_educativos)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLegalizacionTerminales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_legalizacion_propiedad_terminales)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='EcoraeeTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='InfoticTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_infotic_taller_administratic)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCuenticosTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('cuenticos_taller_apertura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.CuenticosTallerApertura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_cuenticos_taller_apertura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDibuarteTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('dibuarte_taller_contenidos_educativos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DibuarteTallerContenidosEducativos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_infotic_dibuarte_taller_contenidos_educativos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoLegalizacionTerminales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('legalizacion_propiedad_terminales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoLegalizacionTerminales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_legalizacion_propiedad_terminales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEcoraeeTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('ecoraee_taller_raee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.EcoraeeTallerRAEE')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_ecoraee_taller_raee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFotograficoTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_administratic)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_administratic)),
                ('foto3', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_administratic)),
                ('foto4', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_administratic)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFotograficoTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_apertura)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_apertura)),
                ('foto3', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_apertura)),
                ('foto4', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_apertura)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFotograficoTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_contenidos_educativos)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_contenidos_educativos)),
                ('foto3', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_contenidos_educativos)),
                ('foto4', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_contenidos_educativos)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFotograficoTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foto1', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_raee)),
                ('foto2', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_raee)),
                ('foto3', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_raee)),
                ('foto4', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_registro_fotografico_taller_raee)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInfoticTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('infotic_taller_administratic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.InfoticTallerAdministratic')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_infotic_taller_administratic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRegistroFotograficoTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('registro_fotografico_taller_apertura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RegistroFotograficoTallerAdministratic')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_fotografico_taller_administratic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRegistroFotograficoTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('registro_fotografico_taller_apertura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RegistroFotograficoTallerApertura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_fotografico_taller_apertura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRegistroFotograficoTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('registro_fotografico_taller_contenidos_educativos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RegistroFotograficoTallerAdministratic')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_fotografico_taller_contenidos_educativos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRegistroFotograficoTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('registro_fotografico_taller_raee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RegistroFotograficoTallerRAEE')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_fotografico_taller_raee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRelatoriaTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRelatoriaTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRelatoriaTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRelatoriaTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RelatoriaTallerAdministratic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_taller_administratic)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RelatoriaTallerApertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_taller_apertura)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RelatoriaTallerContenidosEducativos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_taller_contenidos_educativos)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RelatoriaTallerRAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_taller_raee)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.AlterField(
            model_name='relatoriagraduaciondocentes',
            name='registro_fotografico',
            field=config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_relatoria_graduacion_docentes),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallerraee',
            name='relatoria_taller_raee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RelatoriaTallerRAEE'),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallerraee',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_relatoria_taller_raee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallercontenidoseducativos',
            name='taller_contenidos_educativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RelatoriaTallerContenidosEducativos'),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallercontenidoseducativos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_taller_contenidos_educativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallerapertura',
            name='relatoria_taller_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RelatoriaTallerApertura'),
        ),
        migrations.AddField(
            model_name='registrorelatoriatallerapertura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_relatoria_taller_apertura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorelatoriatalleradministratic',
            name='relatoria_taller_administratic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RelatoriaTallerAdministratic'),
        ),
        migrations.AddField(
            model_name='registrorelatoriatalleradministratic',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_relatoria_taller_administratic', to=settings.AUTH_USER_MODEL),
        ),
    ]
