# Generated by Django 2.0.1 on 2018-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0037_auto_20180703_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolegalizacionterminales',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
