# Generated by Django 2.0.1 on 2018-07-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0038_auto_20180703_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroregistrofotograficotalleradministratic',
            old_name='registro_fotografico_taller_apertura',
            new_name='registro_fotografico_taller_administratic',
        ),
    ]
