# Generated by Django 2.0.1 on 2018-07-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0039_auto_20180703_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroregistrofotograficotallercontenidoseducativos',
            name='registro_fotografico_taller_contenidos_educativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RegistroFotograficoTallerContenidosEducativos'),
        ),
    ]
