# Generated by Django 2.0.1 on 2018-07-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0040_auto_20180703_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolegalizacionterminales',
            name='radicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Radicados'),
            preserve_default=False,
        ),
    ]
