# Generated by Django 2.0.1 on 2018-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0045_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='alias_simec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipios',
            name='alias_simec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
