# Generated by Django 2.0.1 on 2018-07-09 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0046_auto_20180706_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('registro', models.DateField(blank=True, null=True)),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Estrategias')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Municipios')),
            ],
        ),
    ]
