# Generated by Django 2.0.1 on 2018-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0047_docente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docente',
            new_name='Docentes',
        ),
        migrations.AddField(
            model_name='regiones',
            name='cantidad_docentes',
            field=models.IntegerField(default=0),
        ),
    ]
