# Generated by Django 2.0.1 on 2018-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0048_auto_20180709_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='cantidad_docentes',
            field=models.IntegerField(default=0),
        ),
    ]
