# Generated by Django 2.0.1 on 2018-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0049_departamentos_cantidad_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='cantidad_docentes',
            field=models.IntegerField(default=0),
        ),
    ]
