# Generated by Django 2.0.1 on 2018-07-09 20:25

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0050_municipios_cantidad_docentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDocentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=cpe_2018.models.upload_dinamic_dir_file)),
                ('result', models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to=cpe_2018.models.upload_dinamic_dir_file)),
                ('modificados', models.IntegerField(default=0)),
                ('nuevos', models.IntegerField(default=0)),
                ('rechazados', models.IntegerField(default=0)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_db_acceso_docentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
