# Generated by Django 2.0.1 on 2018-07-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0051_actualizaciondocentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentes',
            old_name='diplomado',
            new_name='estrategia',
        ),
        migrations.AddField(
            model_name='docentes',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
