# Generated by Django 2.0.1 on 2018-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0052_auto_20180709_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grupos',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
