# Generated by Django 2.0.1 on 2018-07-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0053_auto_20180710_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos'),
        ),
    ]
