# Generated by Django 2.0.1 on 2018-07-30 16:15

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0054_docentes_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompromisoInscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_documento_compromiso_inscripcion)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoCompromisoInscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('evento_municipal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoCompromisoInscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_documento_compromiso_inscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
