# Generated by Django 2.0.1 on 2018-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0055_documentocompromisoinscripcion_registrodocumentocompromisoinscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentocompromisoinscripcion',
            old_name='nombre',
            new_name='docentes',
        ),
        migrations.AddField(
            model_name='documentocompromisoinscripcion',
            name='eliminar',
            field=models.BooleanField(default=False),
        ),
    ]
