# Generated by Django 2.0.1 on 2018-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0056_auto_20180730_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocompromisoinscripcion',
            name='docentes',
            field=models.TextField(default=''),
        ),
    ]
