# Generated by Django 2.0.1 on 2018-07-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0057_auto_20180730_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregablerutaobject',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Docentes'),
        ),
    ]
