# Generated by Django 2.0.1 on 2018-07-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0058_entregablerutaobject_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodocumentocompromisoinscripcion',
            old_name='evento_municipal',
            new_name='documento_compromiso_inscripcion',
        ),
        migrations.RemoveField(
            model_name='documentocompromisoinscripcion',
            name='docentes',
        ),
        migrations.AddField(
            model_name='documentocompromisoinscripcion',
            name='docentes',
            field=models.ManyToManyField(to='cpe_2018.Docentes'),
        ),
    ]
