# Generated by Django 2.0.1 on 2018-08-02 14:24

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0059_auto_20180730_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaPosesionDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_acta_posesion_docente)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='BaseDatosDocentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_base_datos_docentes)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProyeccionCronograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_documento_proyeccion_cronograma)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoAutoreporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_instrumento_autoreporte)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoEstructuracionPle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_instrumento_estructuracion_ple)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_instrumento_evaluacion)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoHagamosMemoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_instrumento_hagamos_memoria)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='ListadoAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_listado_asistencia)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionActividadPedagogica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_presentacion_actividad_pedagogica)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionApa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_presentacion_apa)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFinalPle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_producto_final_ple)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActaPosesionDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('acta_posesion_docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ActaPosesionDocente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_acta_posesion_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBaseDatosDocentes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('base_datos_docentes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.BaseDatosDocentes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_base_datos_docentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoProyeccionCronograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('documento_proyeccion_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoProyeccionCronograma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_documento_proyeccion_cronograma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInstrumentoAutoreporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('instrumento_autoreporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.InstrumentoAutoreporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_instrumento_autoreporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInstrumentoEstructuracionPle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('instrumento_estructuracion_ple', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.InstrumentoEstructuracionPle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_instrumento_estructuracion_ple', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInstrumentoEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('instrumento_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.InstrumentoEvaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_instrumento_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInstrumentoHagamosMemoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('instrumento_hagamos_memoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.InstrumentoHagamosMemoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_instrumento_hagamos_memoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroListadoAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('listado_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ListadoAsistencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_listado_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPresentacionActividadPedagogica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('presentacion_actividad_pedagogica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.PresentacionActividadPedagogica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_presentacion_actividad_pedagogica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPresentacionApa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('presentacion_apa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.PresentacionApa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_presentacion_apa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProductoFinalPle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('producto_final_ple', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.ProductoFinalPle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_producto_final_ple', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRepositorioActividades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSistematizacionExperiencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RepositorioActividades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_repositorio_actividades)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='SistematizacionExperiencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_sistematizacion_experiencia)),
                ('ver', models.IntegerField(default=0)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('eliminar', models.BooleanField(default=False)),
                ('docentes', models.ManyToManyField(to='cpe_2018.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Grupos')),
            ],
        ),
        migrations.AddField(
            model_name='registrosistematizacionexperiencia',
            name='sistematizacion_experiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.SistematizacionExperiencia'),
        ),
        migrations.AddField(
            model_name='registrosistematizacionexperiencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_sistematizacion_experiencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorepositorioactividades',
            name='repositorio_actividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.RepositorioActividades'),
        ),
        migrations.AddField(
            model_name='registrorepositorioactividades',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_repositorio_actividades', to=settings.AUTH_USER_MODEL),
        ),
    ]
