# Generated by Django 2.0.1 on 2018-08-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0061_auto_20180802_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroactaposesiondocente',
            old_name='acta_posesion_docente',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrobasedatosdocentes',
            old_name='base_datos_docentes',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrodocumentocompromisoinscripcion',
            old_name='documento_compromiso_inscripcion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrodocumentoproyeccioncronograma',
            old_name='documento_proyeccion_cronograma',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroinstrumentoautoreporte',
            old_name='instrumento_autoreporte',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroinstrumentoestructuracionple',
            old_name='instrumento_estructuracion_ple',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroinstrumentoevaluacion',
            old_name='instrumento_evaluacion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroinstrumentohagamosmemoria',
            old_name='instrumento_hagamos_memoria',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrolistadoasistencia',
            old_name='listado_asistencia',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registropresentacionactividadpedagogica',
            old_name='presentacion_actividad_pedagogica',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registropresentacionapa',
            old_name='presentacion_apa',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroproductofinalple',
            old_name='producto_final_ple',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorepositorioactividades',
            old_name='repositorio_actividades',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrosistematizacionexperiencia',
            old_name='sistematizacion_experiencia',
            new_name='modelo',
        ),
    ]
