# Generated by Django 2.0.1 on 2018-08-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0062_auto_20180802_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retoma',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='retoma',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='retoma',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='retoma',
            name='foto4',
        ),
        migrations.RemoveField(
            model_name='retoma',
            name='foto5',
        ),
        migrations.RemoveField(
            model_name='retoma',
            name='foto6',
        ),
    ]
