# Generated by Django 2.0.1 on 2018-08-04 13:26

import cpe_2018.models
from django.db import migrations
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0063_auto_20180803_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoinstitucional',
            old_name='registro_fotografico',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='eventomunicipal',
            old_name='registro_fotografico',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='registroactapostulacion',
            old_name='acta_postulacion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroactualizaciondirectoriomunicipios',
            old_name='actualizacion_directorio_municipios',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroactualizaciondirectoriosedes',
            old_name='actualizacion_directorio_sedes',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrobasedatospostulante',
            old_name='base_datos_postulante',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrocronogramatalleres',
            old_name='cronograma_talleres',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrodocumentolegalizacion',
            old_name='documento_legalizacion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroeventoinstitucional',
            old_name='evento_institucional',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroeventomunicipal',
            old_name='evento_municipal',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorelatoriagraduaciondocentes',
            old_name='relatoria_graduacion_docentes',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='eventoinstitucional',
            name='relatoria',
        ),
        migrations.RemoveField(
            model_name='eventomunicipal',
            name='relatoria',
        ),
        migrations.RemoveField(
            model_name='relatoriagraduaciondocentes',
            name='registro_fotografico',
        ),
        migrations.RemoveField(
            model_name='relatoriagraduaciondocentes',
            name='relatoria',
        ),
        migrations.AddField(
            model_name='relatoriagraduaciondocentes',
            name='file',
            field=config.extrafields.ContentTypeRestrictedFileField(default='', max_length=255, upload_to=cpe_2018.models.upload_dinamic_documento_legalizacion),
            preserve_default=False,
        ),
    ]
