# Generated by Django 2.0.1 on 2018-08-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0064_auto_20180804_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoraeetallerraee',
            old_name='url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='registrocuenticostallerapertura',
            old_name='cuenticos_taller_apertura',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrodibuartetallercontenidoseducativos',
            old_name='dibuarte_taller_contenidos_educativos',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrodocumentolegalizacionterminales',
            old_name='legalizacion_propiedad_terminales',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroecoraeetallerraee',
            old_name='ecoraee_taller_raee',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroinfotictalleradministratic',
            old_name='infotic_taller_administratic',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroregistrofotograficotalleradministratic',
            old_name='registro_fotografico_taller_administratic',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroregistrofotograficotallerapertura',
            old_name='registro_fotografico_taller_apertura',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroregistrofotograficotallercontenidoseducativos',
            old_name='registro_fotografico_taller_contenidos_educativos',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registroregistrofotograficotallerraee',
            old_name='registro_fotografico_taller_raee',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorelatoriatalleradministratic',
            old_name='relatoria_taller_administratic',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorelatoriatallerapertura',
            old_name='relatoria_taller_apertura',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorelatoriatallercontenidoseducativos',
            old_name='taller_contenidos_educativos',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='registrorelatoriatallerraee',
            old_name='relatoria_taller_raee',
            new_name='modelo',
        ),
    ]
