# Generated by Django 2.0.1 on 2018-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0070_cuentascobro_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='estado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
