# Generated by Django 2.0.1 on 2018-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0072_auto_20180809_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='cuentas_cobro_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
