# Generated by Django 2.0.1 on 2018-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0073_rutas_cuentas_cobro_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentascobro',
            name='delta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
