# Generated by Django 2.0.1 on 2018-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0074_auto_20180809_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='data_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
