# Generated by Django 2.0.1 on 2018-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0075_cuentascobro_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='valores_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
