# Generated by Django 2.0.1 on 2018-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0076_cuentascobro_valores_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentascobro',
            name='valores_json',
            field=models.TextField(default='[]'),
        ),
    ]
