# Generated by Django 2.0.1 on 2018-08-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0078_auto_20180810_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentascobro',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_actualizacion_cuentas_cobro', to=settings.AUTH_USER_MODEL),
        ),
    ]
