# Generated by Django 2.0.1 on 2018-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0080_retoma_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadoasistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatoriatalleradministratic',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatoriatallerapertura',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatoriatallercontenidoseducativos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatoriatallerraee',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
