# Generated by Django 2.0.1 on 2018-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0082_auto_20180817_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='actividades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docentes',
            name='valor_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docentes',
            name='valor_unitario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
