# Generated by Django 2.0.1 on 2018-08-23 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0083_auto_20180822_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consecutivo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_red', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actaposesiondocente',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='actapostulacion',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='actualizaciondirectoriomunicipios',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='actualizaciondirectoriosedes',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='basedatosdocentes',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='basedatospostulante',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='cronogramatalleres',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='cuenticostallerapertura',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='dibuartetallercontenidoseducativos',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='documentocompromisoinscripcion',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='documentolegalizacion',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='documentolegalizacionterminales',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='documentoproyeccioncronograma',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='ecoraeetallerraee',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='eventoinstitucional',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='eventomunicipal',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='infotictalleradministratic',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='instrumentoautoreporte',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='instrumentoestructuracionple',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='instrumentoevaluacion',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='instrumentohagamosmemoria',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='listadoasistencia',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='presentacionactividadpedagogica',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='presentacionapa',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='productofinalple',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='registrofotograficotalleradministratic',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='registrofotograficotallerapertura',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='registrofotograficotallercontenidoseducativos',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='registrofotograficotallerraee',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='relatoriagraduaciondocentes',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='relatoriatalleradministratic',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='relatoriatallerapertura',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='relatoriatallercontenidoseducativos',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='relatoriatallerraee',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='repositorioactividades',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='retoma',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
        migrations.AddField(
            model_name='sistematizacionexperiencia',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
    ]
