# Generated by Django 2.0.1 on 2018-08-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0085_auto_20180824_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Regiones'),
            preserve_default=False,
        ),
    ]
