# Generated by Django 2.0.1 on 2018-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0086_red_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='red',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
