# Generated by Django 2.0.1 on 2018-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0088_auto_20180824_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='estrategia',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
