# Generated by Django 2.0.1 on 2018-08-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0089_red_estrategia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregablerutaobject',
            name='radicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Radicados'),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='radicado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
