# Generated by Django 2.0.1 on 2018-08-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0090_auto_20180826_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retoma',
            name='cedula',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retoma',
            name='rector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
