# Generated by Django 2.0.1 on 2018-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0097_auto_20180907_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaposesiondocente',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_2', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='basedatosdocentes',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_3', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='documentocompromisoinscripcion',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_1', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='documentoproyeccioncronograma',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_4', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='instrumentoautoreporte',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_6', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='instrumentoestructuracionple',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_13', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='instrumentoevaluacion',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_12', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='instrumentohagamosmemoria',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_8', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='listadoasistencia',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_5', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='presentacionactividadpedagogica',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_9', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='presentacionapa',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_7', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='productofinalple',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_14', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='repositorioactividades',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_10', to='cpe_2018.Docentes'),
        ),
        migrations.AddField(
            model_name='sistematizacionexperiencia',
            name='docentes_rechazados',
            field=models.ManyToManyField(blank=True, related_name='rechazados_11', to='cpe_2018.Docentes'),
        ),
    ]
