# Generated by Django 2.0.1 on 2018-09-11 22:14

import cpe_2018.models
from django.db import migrations
import config.extrafields
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0098_auto_20180911_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red',
            name='file2',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to=cpe_2018.models.upload_dinamic_red),
        ),
    ]
