# Generated by Django 2.0.1 on 2018-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0099_auto_20180911_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='retoma',
            name='bolsas_empacadas',
            field=models.IntegerField(default=0),
        ),
    ]
