# Generated by Django 2.0.1 on 2018-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0100_retoma_bolsas_empacadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='retoma',
            name='estado_observacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
