# Generated by Django 2.0.1 on 2018-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0101_retoma_estado_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='observaciones',
            field=models.TextField(default=''),
        ),
    ]
