# Generated by Django 2.0.1 on 2018-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0102_cuentascobro_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentascobro',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
