# Generated by Django 2.0.1 on 2018-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0104_auto_20180919_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadoasistencia',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productofinalple',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repositorioactividades',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
