# Generated by Django 2.0.1 on 2018-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0105_auto_20180919_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestamonitoreo',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
