# Generated by Django 2.0.1 on 2018-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0106_encuestamonitoreo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='presupuesto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
