# Generated by Django 2.0.1 on 2018-10-08 20:00

import cpe_2018.models
from django.db import migrations, models
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0107_entregables_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionLupaap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tablero_control', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_actualizacion_lupaap)),
                ('informe_lupaap', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_actualizacion_lupaap)),
                ('resultado', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_actualizacion_lupaap)),
            ],
        ),
    ]
