# Generated by Django 2.0.1 on 2018-10-08 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0108_actualizacionlupaap'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionlupaap',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
