# Generated by Django 2.0.1 on 2018-10-09 13:10

import cpe_2018.models
from django.db import migrations
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0109_actualizacionlupaap_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionlupaap',
            name='informe_lupaap_json',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_actualizacion_lupaap),
        ),
        migrations.AddField(
            model_name='actualizacionlupaap',
            name='tablero_control_json',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_actualizacion_lupaap),
        ),
    ]
