# Generated by Django 2.0.1 on 2018-10-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0110_auto_20181009_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionlupaap',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red'),
        ),
    ]
