# Generated by Django 2.0.1 on 2018-10-22 15:50

import cpe_2018.models
from django.db import migrations, models
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0112_auto_20181010_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionAutoreporteEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tablero_control', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_actualizacion_autoreporte_evaluacion)),
                ('tablero_control_json', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_actualizacion_autoreporte_evaluacion)),
                ('resultado', config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_actualizacion_autoreporte_evaluacion)),
            ],
        ),
    ]
