# Generated by Django 2.0.1 on 2018-10-25 16:36

import cpe_2018.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import config.extrafields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0113_actualizacionautoreporteevaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegalizacionTerminalesValle1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_legalizacion_propiedad_terminales_valle_1)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='', max_length=100)),
                ('radicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Radicados')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLegalizacionTerminalesValle2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('file', config.extrafields.ContentTypeRestrictedFileField(max_length=255, upload_to=cpe_2018.models.upload_dinamic_legalizacion_propiedad_terminales_valle_2)),
                ('ver', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('novedades', models.CharField(default='', max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='', max_length=100)),
                ('radicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Radicados')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Red')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Rutas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoLegalizacionTerminalesValle1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoLegalizacionTerminalesValle1')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_legalizacion_propiedad_terminales_valle1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDocumentoLegalizacionTerminalesValle2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('delta', models.CharField(max_length=10000)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.DocumentoLegalizacionTerminalesValle2')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_legalizacion_propiedad_terminales_valle2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
