# Generated by Django 2.0.1 on 2018-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0114_documentolegalizacionterminalesvalle1_documentolegalizacionterminalesvalle2_registrodocumentolegaliz'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
