# Generated by Django 2.1.3 on 2018-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0116_actualizacionproductosfinales'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregablerutaobject',
            name='para_pago',
            field=models.BooleanField(default=True),
        ),
    ]
