# Generated by Django 2.1.3 on 2018-12-27 20:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0118_auto_20181220_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascobro',
            name='liquidacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuentascobro',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpe_2018.Cortes'),
        ),
        migrations.AlterField(
            model_name='cuentascobro',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentascobro',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentascobro',
            name='valor',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='COP', max_digits=10, null=True),
        ),
    ]
