# Generated by Django 2.1.3 on 2019-01-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0119_auto_20181227_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciones',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
