# Generated by Django 2.1.3 on 2019-01-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0120_liquidaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciones',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
