# Generated by Django 2.1.3 on 2019-01-03 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpe_2018', '0121_liquidaciones_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidaciones',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_actualizacion_liquidacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
