# Generated by Django 2.1.3 on 2019-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0122_auto_20190103_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='efectivo',
            field=models.BooleanField(default=False),
        ),
    ]
