# Generated by Django 2.1.3 on 2019-01-10 13:59

import cpe_2018.models
from django.db import migrations
import config.extrafields


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0124_docentes_producto_final_andes'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciones',
            name='file3',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, max_length=255, null=True, upload_to=cpe_2018.models.upload_dinamic_liquidaciones),
        ),
    ]
