# Generated by Django 2.1.3 on 2019-01-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe_2018', '0126_auto_20190110_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='permitir_recarga',
            field=models.BooleanField(default=False),
        ),
    ]
