# Generated by Django 2.0.1 on 2018-05-16 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entes_territoriales.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entes_territoriales', '0003_soportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entes_territoriales.Reuniones')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_hito_reunion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delta', models.CharField(max_length=10000)),
                ('hito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entes_territoriales.Hito')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entes_territoriales.Reuniones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_reunion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
