# Generated by Django 2.0.1 on 2018-05-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entes_territoriales', '0004_hito_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_creacion_registro_reunion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
