# Generated by Django 2.0.1 on 2018-05-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0005_auto_20180517_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario_creacion',
        ),
    ]
