# Generated by Django 2.0.1 on 2018-05-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0006_remove_registro_usuario_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hito',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='hito',
            name='reunion',
        ),
        migrations.RemoveField(
            model_name='hito',
            name='usuario_creacion',
        ),
    ]
