# Generated by Django 2.0.1 on 2018-05-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0007_auto_20180521_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entes_territoriales.Reuniones'),
            preserve_default=False,
        ),
    ]
