# Generated by Django 2.0.1 on 2018-05-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0008_hito_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entes_territoriales.Contactos'),
        ),
    ]
