# Generated by Django 2.0.1 on 2018-05-30 16:02

from django.db import migrations, models
import django.utils.timezone
import entes_territoriales.models


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0009_registro_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='clase',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hito',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hito',
            name='foto_1',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
        migrations.AddField(
            model_name='hito',
            name='foto_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
        migrations.AddField(
            model_name='hito',
            name='foto_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
        migrations.AddField(
            model_name='hito',
            name='foto_4',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
    ]
