# Generated by Django 2.0.1 on 2018-05-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0011_auto_20180530_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniones',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Municipios'),
        ),
    ]
