# Generated by Django 2.0.1 on 2018-06-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0014_auto_20180620_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniones',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
