# Generated by Django 2.1.5 on 2019-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0015_reuniones_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contactos',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='comunidad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='lenguas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='nombres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='resguardo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
