# Generated by Django 2.1.5 on 2019-11-27 02:50

from django.db import migrations, models
import entes_territoriales.models


class Migration(migrations.Migration):

    dependencies = [
        ('entes_territoriales', '0016_auto_20191126_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hito',
            name='clase',
        ),
        migrations.AddField(
            model_name='hito',
            name='file2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
        migrations.AddField(
            model_name='hito',
            name='file3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=entes_territoriales.models.upload_dinamic_hito),
        ),
    ]
