# Generated by Django 2.0.1 on 2018-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level1',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level2',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level3',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level4',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level5',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level6',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level7',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='level8',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='level1',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level2',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level3',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level4',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level5',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level6',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level7',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level8',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
