# Generated by Django 2.0.1 on 2018-06-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20180606_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level8',
            name='nivel',
        ),
    ]
